services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: root_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "25432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet


  # Опционально: pgAdmin для управления БД
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - dbnet
    depends_on:
      - postgres


volumes:
  postgres-data:


networks:
  dbnet:
    driver: bridge